# Generated by Django 4.2.8 on 2023-12-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0004_book_description'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_books',
            field=models.ManyToManyField(related_name='favorited_users', to='book_catalog.book'),
        ),
    ]
